/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ButtonComponent: typeof import('./components/Counter/ButtonComponent.vue')['default']
    CountComponent: typeof import('./components/Counter/CountComponent.vue')['default']
    Root: typeof import('./components/Counter/Root.vue')['default']
    TabItem: typeof import('./components/Tab/TabItem.vue')['default']
    Tabs: typeof import('./components/Tab/Tabs.vue')['default']
  }
}
